name: "u-blox GPS RTK"
version: "0.2.5"
slug: ublox_gps_rtk
description: "HomeAssistant add-in for u-blox ZED-F9P GPS with NTRIP RTK corrections"
url: "https://github.com/greenforge-labs/ublah"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Web interface for GPS status and configuration"
devices:
  - "/dev/ttyUSB0:/dev/ttyUSB0:rwm"
  - "/dev/ttyUSB1:/dev/ttyUSB1:rwm"
  - "/dev/ttyACM0:/dev/ttyACM0:rwm"
  - "/dev/ttyACM1:/dev/ttyACM1:rwm"
udev: true
privileged:
  - SYS_RAWIO
options:
  gps_device: "/dev/ttyUSB0"
  gps_baudrate: 38400
  update_rate_hz: 1
  constellation: "GPS+GLONASS+GALILEO+BEIDOU"
  ntrip_enabled: true
  ntrip_host: ""
  ntrip_port: 2101
  ntrip_mountpoint: ""
  ntrip_username: ""
  ntrip_password: ""
  homeassistant_url: "http://supervisor/core"
  homeassistant_token: ""
schema:
  gps_device: "str"
  gps_baudrate: "int(9600,115200)"
  update_rate_hz: "int(1,10)" 
  constellation: "list(GPS|GLONASS|GALILEO|BEIDOU|QZSS|SBAS)"
  ntrip_enabled: "bool"
  ntrip_host: "str?"
  ntrip_port: "int(1,65535)?"
  ntrip_mountpoint: "str?"
  ntrip_username: "str?"
  ntrip_password: "str?"
  homeassistant_url: "str"
  homeassistant_token: "str?"
